name: Publish
on:
  push:
    branches:
      - main
      - dev

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm build
      - run: pnpm test    
      - name: Publish package
        working-directory: packages/tauri-api-adapter
        run: npx jsr publish
